apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: jaip
  title: JAIP
  description: The system for the JAIP web application.
spec:
  type: system
  owner: jaip
  system: jaip
  lifecycle: preview
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jaip-backend
  description: The JAIP Online Application Backend
  annotations:
    gitlab.com/project-id: "66184988"
  links:
    - url: https://jaip-backend.apps.prod.cirrostratus.org/
      title: Production Application
    - url: https://jaip-backend.apps.test.cirrostratus.org/
      title: Test Application
spec:
  type: service
  owner: jaip
  lifecycle: preview
  system: jaip-backend
  providesApis:
    - api:jaip-backend-api
  consumesApis:
    - api:session-service-gql
  dependsOn:
    - component:session-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jaip-backend-api
  title: JAIP Backend API
  description: API for accessing JAIP services
  links:
    - url: https://jaip-backend.apps.prod.cirrostratus.org/docs
      title: Production Swagger
    - url: https://jaip-backend.apps.test.cirrostratus.org/docs
      title: Test Swagger
spec:
  type: openapi
  owner: group:labs
  lifecycle: production
  system: jaip-backend
  definition:
  # This is currently using the test URL. This should be updated to prod once it's actually in use,
  # but it's also not really that important, as this shouldn't generally be relied upon for much of anything.
  # See: https://github.com/backstage/backstage/issues/17736
    $text: https://jaip-backend.apps.test.cirrostratus.org/docs/json

