apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: jaip
  title: JSTOR Access in Prisons (JAIP)
  description: The system for the JAIP web application.
  tags:
    - jaip
    - online-pep
    - node
    - vue
    - javascript
    - typescript
    - labs
    - api
spec:
  type: system
  owner: jaip
  system: jaip
  lifecycle: beta
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jaip-backend
  title: JAIP Backend
  description: The JAIP Online Application Backend
  annotations:
    gitlab.com/project-id: "66184988"
  links:
    - url: https://jaip-backend.apps.prod.cirrostratus.org/
      title: Production Application
    - url: https://jaip-backend.apps.test.cirrostratus.org/
      title: Test Application
spec:
  type: service
  owner: jaip
  lifecycle: beta
  system: jaip
  providesApis:
    - api:jaip-backend-api
  consumesApis:
    - api:session-service-gql
  dependsOn:
    - component:session-service
    - component:search3
    - component:search-service
    - component:search-snippet-service
    - resource:ale-query-service
    - component:cedar-delivery-service
  # The dependency on the ITHAKA CLI is a dev dependency. The Polaris sidecar
  # is a production/test dependency. Backstage isn't great at making environmental 
  # distinctions.
    - component:ithaka-cli
    - component:polaris
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jaip-backend-api
  title: JAIP Backend API
  description: API for accessing JAIP services
  links:
    - url: https://jaip-backend.apps.prod.cirrostratus.org/docs
      title: Production Swagger
    - url: https://jaip-backend.apps.test.cirrostratus.org/docs
      title: Test Swagger
spec:
  type: openapi
  owner: jaip
  lifecycle: beta
  system: jaip
  # This definition is currently using the test URL. This should be updated to prod once it's actually in use,
  # but it's also not really that important, as this shouldn't generally be relied upon for much of anything.
  # See: https://github.com/backstage/backstage/issues/17736
  definition:
    $text: https://jaip-backend.apps.test.cirrostratus.org/docs/json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jaip-test-db
  title: JAIP Test Database
  description: Stores the data for the test environment of the JAIP application
  environment: test
  links:
    - url: ./cloudformation/rds.test.yaml
      title: RDS CloudFormation Template for the Test Database Cluster
spec:
  type: database
  owner: jaip
  system: jaip
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jaip-prod-db
  title: JAIP Production Database
  description: Stores the data for the production environment of the JAIP application
  environment: prod
  links:
    - url: ./cloudformation/rds.prod.yaml
      title: RDS CloudFormation Template for the Production Database Cluster
spec:
  type: database
  owner: jaip
  system: jaip
