# See the base values file at
# https://gitlab.com/capstan/pow/cicd-infrastructure/-/blob/master/helm-charts/capstan-app/values.yaml .
# Values set here override those.

# Variables set in the pipeline are available here.
commitHash: $CI_COMMIT_SHA

requiredTags:
  owner: $ITHAKA_OWNER
  app: jaip-backend
  environment: $ENVIRONMENT
  businessUnit: $ITHAKA_BUSINESS_UNIT

testSecret: test-secret-name

extraEnv:
  - name: JAIP_TEST_SECRET
    valueFrom:
      secretKeyRef:
        key: JAIP_TEST_SECRET
        name: test-secret-name


registerInEureka: true
serviceLocatable: true
eurekaServiceName: $EUREKA_SERVICE_NAME

# We'll likely want to enable these in future, but there are things we need to
# configure first.
prometheus:
  enable: false

# The port that your application itself listens on.
internalPort: 8080
healthcheckPath: /healthz

spec:
  template:
    spec:
      containers:
        ports:
          containerPort: 8080

# Opt in to the new Sirius sidecar container that ensures this application is discoverable in Capstan, and replaces ITHAKA's legacy sidecar container
# https://gitlab.com/capstan/pow/cicd-infrastructure/-/blob/master/helm-charts/capstan-app/values.yaml?ref_type=heads#L85
sirius:
  enabled: true

# Polaris is the new service discovery sidecar. Set this to enabled if you
# want to use this instead of the deprecated Sidecar.
#
# This will remove The Sidecar from the deployment if polaris.enabled is set
# to true.
#
# For more information about Polaris, check out the documentation in Backstage:
# https://capstan-backstage.apps.prod.cirrostratus.org/catalog/default/component/polaris/docs
polaris:
  enabled: true
  debug: false
  port: 8888
