apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.databaseSecretName }}
  labels:
    ithaka/app: credit-mobility-site
spec:
  refreshInterval: 1h
  target:
    name: {{ .Values.databaseSecretName }}
  secretStoreRef:
    name: aws-ssm-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: DX_CA_PASS
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.DX_CA_PASS }}
    - secretKey: DX_CA_DB
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.DX_CA_DB }}
    - secretKey: DX_CA_USER
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.DX_CA_USER }}
    - secretKey: DX_CA_URL
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.DX_CA_URL }}
