apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.databaseSecretName }}
  labels:
    ithaka/app: jaip-backend
    ithaka/app: {{ .Values.requiredTags.app }}
    ithaka/environment: {{ .Values.requiredTags.environment }}
    ithaka/owner: {{ .Values.requiredTags.owner }}
    ithaka/businessUnit: {{ .Values.requiredTags.businessUnit }}
spec:
  refreshInterval: 1h
  target:
    name: {{ .Values.databaseSecretName }}
  secretStoreRef:
    name: aws-ssm-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: JAIP_TEST_SECRET
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.JAIP_TEST_SECRET }}
